### ISSUE TITLE
Buses moving back and forth

### ISSUE THREAD

**Issue by cjer** [hasadna/open-bus#212] opened 2019-05-23 14:23 UTC
The last few weeks I found numerous examples in SIRI of buses moving back and forth. 
I'm looking at records of the same `bus_id`, `route_id`, `planned_start_time`, `trip_id` move forward in time (`time_recorded`), while its coordinates moves frantically back and forth. 
Example ([link ](http://35.192.116.75/en-US/app/open-bus/siri_investigator?latest=1558558800&form.time_setter.earliest=-30d%40d&form.time_setter.latest=now&form.agency_id=5&form.stop_city=%D7%A8%D7%9E%D7%AA%20%D7%92%D7%9F&form.route_short_name=45&form.hour_min=0&form.hour_max=24&earliest=1558472400.000000&form.earliest=1558472400.000000&form.route_id=2466&form.planned_start_time=16%3A20%3A00) for those with access to splunk) - route_short_name=45, route_id=2466, bus_id=7718:
![image](https://user-images.githubusercontent.com/9987721/58260178-a8a13800-7d7e-11e9-963e-472708feb0fb.png)
Notice that all coordinates are on the expected shape, but their `time_recorded` looks like it is randomly scattered.
I have more examples from different routes, buses and times,  and it looks like the phenomenon is very frequent.

Any ideas? In previous times, cases like these turned out to be from different buses that report as if they're doing the same trip, but this doesn't seem to be the case here.

**Comment by evyatark** [comment] 2019-05-24 03:23
בבקשה שלח עוד 2-3 דוגמאות
ובכל דוגמה צריך גם תאריך
ושעת יציאה או
Trip Id

**Comment by evyatark** [comment] 2019-05-24 03:24
בבקשה שלח עוד 2-3 דוגמאות
ובכל דוגמה צריך גם תאריך
ושעת יציאה או
Trip Id
אני אבדוק על הנתונים הכי גולמיים שיש לנו כדי לוודא שזה לא בעיה ב
Splunk

**Comment by cjer** [comment] 2019-05-24 08:01
All the info you need is in the dashboards or URL parameters
[1](http://35.192.116.75/en-US/app/open-bus/siri_investigator?latest=1558558800&form.time_setter.earliest=-30d%40d&form.time_setter.latest=now&form.agency_id=5&form.stop_city=%D7%A8%D7%9E%D7%AA%20%D7%92%D7%9F&form.route_short_name=45&form.hour_min=0&form.hour_max=24&earliest=1558472400.000000&form.earliest=1558472400.000000&form.route_id=2466&form.planned_start_time=17%3A35%3A00)
[2](http://35.192.116.75/en-US/app/open-bus/siri_investigator?latest=1558558800&form.time_setter.earliest=-30d%40d&form.time_setter.latest=now&form.agency_id=5&form.stop_city=%D7%A8%D7%9E%D7%AA%20%D7%92%D7%9F&form.route_short_name=45&form.hour_min=0&form.hour_max=24&earliest=1558472400.000000&form.earliest=1558472400.000000&form.route_id=2467&form.planned_start_time=17%3A35%3A00)
[3](http://35.192.116.75/en-US/app/open-bus/siri_investigator?latest=1558558800&form.time_setter.earliest=-30d%40d&form.time_setter.latest=now&form.agency_id=5&form.stop_city=%D7%A8%D7%9E%D7%AA%20%D7%92%D7%9F&form.route_short_name=161&form.hour_min=0&form.hour_max=24&earliest=1558472400.000000&form.earliest=1558472400.000000&form.route_id=9807&form.planned_start_time=17%3A39%3A00)
[4](http://35.192.116.75/en-US/app/open-bus/siri_investigator?latest=1558558800&form.time_setter.earliest=-30d%40d&form.time_setter.latest=now&form.agency_id=5&form.stop_city=%D7%A8%D7%9E%D7%AA%20%D7%92%D7%9F&form.route_short_name=161&form.hour_min=0&form.hour_max=24&earliest=1558472400.000000&form.earliest=1558472400.000000&form.route_id=9807&form.planned_start_time=18%3A30%3A00)

**Comment by evyatark** [comment] 2019-05-25 06:43
Definitely there is a problem, we can see it also in the raw logs.
I changed logging to log all XMLs arriving from MOT.
Dan - if you can find an example from **after** Saturday 2019-05-25 7:30, I will be able to compare it to the raw XML that arrived, and then we can know if the source of the problem is our code or not.

**Comment by cjer** [comment] 2019-05-27 16:20
Examples from yesterday:
[1](http://35.192.116.75/en-US/app/open-bus/siri_investigator?latest=1558904400&form.time_setter.earliest=-30d%40d&form.time_setter.latest=now&form.agency_id=5&form.stop_city=*&form.route_short_name=3&form.hour_min=0&form.hour_max=24&earliest=1558818000.000000&form.earliest=1558818000.000000&form.route_id=2243&form.planned_start_time=12%3A05%3A00)

**Comment by evyatark** [comment] 2019-05-27 18:04
After investigation - the problem is not on our side. We receive from Siri server incorrect values in the "RecordedAtTime" field.

Attaching here some files with an example and detailed explanation.

[Summary Of Problem.log](https://github.com/hasadna/open-bus/files/3224663/Summary.Of.Problem.log)


![Screenshot of query1 and the previous GPS point](https://user-images.githubusercontent.com/4737148/58434129-cc3be980-80c2-11e9-86bc-3561e518a760.png)
![Screenshot of query2 and query3](https://user-images.githubusercontent.com/4737148/58434134-d2ca6100-80c2-11e9-8ef2-2b2fb2f6cd0e.png)


[query1.log](https://github.com/hasadna/open-bus/files/3224664/query1.log)
[query2.log](https://github.com/hasadna/open-bus/files/3224665/query2.log)
[query3.log](https://github.com/hasadna/open-bus/files/3224666/query3.log)




After investigation by Dan and me, it appears that the problem is in the XML that we receive from SIRI server (MOT).
We saw many occurrences of this problem.
I attach here a detailed investigation of one such case.
date 2019-05-26, Line 3 of Dan (route ID 2243), departure at 12:05. (trip ID 39204691)
I attach files with the full explanation, the full XML responses we received from SIRI server, and screenshots of the points on a map.


Query #1
    ResponseTimestamp>2019-05-26T12:22:05
    RecordedAtTime>2019-05-26T12:12:30          <==== Incorrect value of recordedAt
    DatedVehicleJourneyRef>39204691
    VehicleLocation>>34.76801300048828<>32.0455207824707<>

Query #2
    ResponseTimestamp>2019-05-26T12:23:05
    RecordedAtTime>2019-05-26T12:23:20          <==== Reasonable value of recordedAt
    DatedVehicleJourneyRef>39204691
    VehicleLocation>>34.76584243774414<>32.0423469543457>

Query #3
    ResponseTimestamp>2019-05-26T12:24:05
    RecordedAtTime>2019-05-26T12:17:57          <==== Incorrect value of recordedAt
    DatedVehicleJourneyRef>39204691
    VehicleLocation>>34.76538848876953<>32.040531158447266<>

**Comment by cjer** [comment] 2019-05-27 18:37
Here is the [search ](http://35.192.116.75/en-US/app/open-bus/report?s=%2FservicesNS%2Fdanb%2Fopen-bus%2Fsaved%2Fsearches%2FFind%2520weird%2520distance%2520hops&sid=danb__danb_b3Blbi1idXM__RMD5cfd83b3f97c03af1_at_1558982197_80&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=1558472400&latest=1558558800) I used to find the examples

**Comment by AvivSela** [comment] 2019-05-29 10:12
The documentation file about SIRI format in MOT says that: (page 15,18 https://www.gov.il/BlobFolder/generalpage/real_time_information_siri/he/ICD-SM.pdf)

- ResponseTimestamp - מועד השדר
- RecordedAtTime - הזמן בו המידע נרשם במערכת

1. Is that mean that the ResponseTimestamp should occur after RecordedAtTime? it seems like even the "Reasonable value of recordedAt" is greater than ResponseTimestamp. 
2. is it not better to based our analysis on recordedAt field?

Is this issue fixed? if not, are we going to talk with MOT to fix this issue? is there a need to open other issue for that?

**Comment by cjer** [comment] 2019-05-29 10:16
The issue is not fixed - we know the problem is in the original MOT response, and not in our systems.
We should talk to MOT about this.

**Comment by evyatark** [comment] 2019-05-29 11:47
regarding:
ResponseTimestamp - מועד השדר
RecordedAtTime - הזמן בו המידע נרשם במערכת

The words used above might be a bit vague. The actual meaning of the fields are:

RecordedAtTime - the point in time when the vehicle was at the GPS point (that is attached to this time). Or in other words, the point in time when the GPS device measured the GPS point.

ResponseTimestamp - the point in time when the SIRI MOT server sent the XML response to our query ("our query" means the SOAP XML HTTP request that siri-collector sent to SIRI MOT server).

**Comment by evyatark** [comment] 2019-05-29 11:50
> The issue is not fixed - we know the problem is in the original MOT response, and not in our systems.
> We should talk to MOT about this.

I would prefer closing this issue and opening another issue that says "talk to MOT about this" (or any other words you want to use), and that issue should include a link to here so you don't have to write the explanations all over again.

But this is my opinion, if you have a different one it's OK by me.

**Closed** 2019-08-19 17:18 UTC
Labels: Data, Question
