### ISSUE TITLE
Wrong parameter doesn't raise error

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#378] opened 2022-02-27 20:25 UTC
I think the API should raise an error when a wrong parameter is used, as getting data back (without filtering) is confusing for users.

see example from siri_routes. I forgot the "s" in "operator_ref" but getting back wrong results instead of an error.

![image](https://user-images.githubusercontent.com/42667498/155898562-c0ad12c5-32a3-4ebf-bdfa-20b07d5de8eb.png)

**Comment by OriHoch** [comment] 2022-02-28 07:23
duplicate of #362

**Closed as completed by OriHoch** 2022-02-28 07:23 UTC
