### ISSUE TITLE
Missing rows in siri_vehicle_locations

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#388] opened 2022-03-11 11:42 UTC
I've performed this test:

1. get SIRI raw data from 6 files: 
`yyyy = "2022"
mm = "03"
dd = "01"
hour = "07"
minutes = ["00","01","02","03","04","05"]`

and filter the output
`siri_source[(siri_source.OperatorRef==3)&
                     (siri_source.RecordedAtTime.dt.time.astype(str).between('09:00:00','09:06:00')`

2. call the API for the same data:

`siri_vehicle_locations = pd.DataFrame(stride.iterate('/siri_vehicle_locations/list', {
    'recorded_at_time_from': datetime.datetime(int(yyyy),int(mm), int(dd), int(hour), int(minutes[0]),
                                                                                   tzinfo=tz.gettz('UTC')),
    'recorded_at_time_to': datetime.datetime(int(yyyy),int(mm), int(dd), int(hour), int(minutes[len(minutes)-1]),
                                                                                    tzinfo=tz.gettz('UTC')),
    'siri_routes__operator_ref': '3',
}, limit=100000))`

and localize the dates

4.  merge the outputs by the key `'recorded_at_time','siri_route__line_ref','siri_route__operator_ref','siri_ride__scheduled_start_time',
           'lon','lat','siri_ride__vehicle_ref'` (left join from source data to Stride)

Conclusions: 

* Match rate is very high (!):
![image](https://user-images.githubusercontent.com/42667498/157860388-98860e5b-2a57-4080-b40c-e151e5ce94d1.png)

(the first minute missing rows might be because I haven't passed a seconds settings to the API?)  

* Example for a missing data:
![image](https://user-images.githubusercontent.com/42667498/157859296-95cbd455-509f-4e5a-80d7-ca3c8499d6ad.png)

Any idea why some rows are missing? is there a way to deep dive why some rows are missing?
In general it seems very good match rate, so I am not sure how to prioritize this issue.

**Comment by OriHoch** [comment] 2022-03-13 07:53
Good catch! There was indeed a problem which occured only in rare cases, I fixed it for new vehicle locations and will now check about fixing old data as well

**Comment by OriHoch** [comment] 2022-03-20 06:28
@EyalBerger you can check the fix for recent data (last 5 days)
I'm currently processing old data, will update here when done

**Comment by EyalBerger** [comment] 2022-03-21 15:35
@OriHoch - from some reason I can't call the siri_vehicle_locations now. From python the cell is running for a long time, and from the [web API ](https://open-bus-stride-api.hasadna.org.il/docs#/siri/list__siri_vehicle_locations_list_get) I get an error when querying for line ref "12406" without any other filters:

requested url: `https://open-bus-stride-api.hasadna.org.il/siri_vehicle_locations/list?siri_routes__line_ref=12406 `

error message (500): `Can't determine join between 'siri_vehicle_location' and 'siri_ride_stop'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.`

**Comment by OriHoch** [comment] 2022-03-21 15:44
@EyalBerger please open a separate issue

**Comment by OriHoch** [comment] 2022-03-22 06:16
there is a bug which prevents testing this issue via the API

the bug will be handled in https://github.com/hasadna/open-bus-stride-api/issues/10 - deleting the comments to keep issue relevant

**Comment by OriHoch** [comment] 2022-03-22 06:18
@EyalBerger you can also test via the DB using Redash or I can give you direct read-only access too

**Comment by OriHoch** [comment] 2022-03-22 15:35
Full data should be available since 15 February 2022

**Comment by EyalBerger** [comment] 2022-03-22 16:47
Thanks @OriHoch - for now I'll wait until [that issue](https://github.com/hasadna/open-bus-stride-api/issues/10) is resolved for rechecking the missing rows issue.

**Comment by OriHoch** [comment] 2022-03-23 11:42
@EyalBerger issue is resolved, you can get siri vehicle locations from api now

**Comment by EyalBerger** [comment] 2022-03-27 17:36
Hi @OriHoch. thanks for taking care of it. 
I run my test again for 2020-03-01 09:00 - 09:05 IST. The overall coverage is slightly better now (~90%), but there are still gaps, and I didn't managed to understand why. Am I checking a problematic/too told date? 
If not, it might worth checking why those rows are missing. For example this row can be found in SIRI source files (`2022/03/01/07/04`) but not in the db:
`line_ref: 10228`
`RecordedAtTime: 2022-03-01 09:03:39+02:00`
`OriginAimedDepartureTime: 2022-03-01 08:00:00+02:00`

In the db there are records before and after this missing row:
![image](https://user-images.githubusercontent.com/42667498/160293498-1750363a-c21a-4aa5-b59f-f3d8f9fd6aa6.png)

**Comment by OriHoch** [comment] 2022-03-27 20:42
If you will write the API request you made or Python code you ran I could check what's the problem, but in general, the vehicle location that you refer to exists in DB and can be returned from the API using the following URL:
```
https://open-bus-stride-api.hasadna.org.il/siri_vehicle_locations/list?recorded_at_time_from=2022-03-01T07%3A03%3A39%2B00%3A00&recorded_at_time_to=2022-03-01T07%3A03%3A39%2B00%3A00&siri_routes__line_ref=10228&siri_rides__schedualed_start_time_from=2022-03-01T06%3A00%3A00%2B00%3A00&siri_rides__schedualed_start_time_to=2022-03-01T06%3A00%3A00%2B00%3A00
```
The response:
```
[
  {
    "id": 71559502,
    "siri_snapshot_id": 22798,
    "siri_ride_stop_id": 34880660,
    "recorded_at_time": "2022-03-01T07:03:39+00:00",
    "lon": 35.158318,
    "lat": 31.761864,
    "bearing": 346,
    "velocity": 47,
    "distance_from_journey_start": 20842,
    "distance_from_siri_ride_stop_meters": 479,
    "siri_snapshot__snapshot_id": "2022/03/01/07/04",
    "siri_route__id": 338,
    "siri_route__line_ref": 10228,
    "siri_route__operator_ref": 3,
    "siri_ride__id": 1400821,
    "siri_ride__journey_ref": "2022-03-01-5496576",
    "siri_ride__scheduled_start_time": "2022-03-01T06:00:00+00:00",
    "siri_ride__vehicle_ref": "7809769",
    "siri_ride__first_vehicle_location_id": 72047263,
    "siri_ride__last_vehicle_location_id": 71547539,
    "siri_ride__duration_minutes": 70,
    "siri_ride__gtfs_ride_id": 1630530
  }
]
```

**Comment by EyalBerger** [comment] 2022-03-28 17:50
Let me double check my pipeline. thanks!

**Comment by EyalBerger** [comment] 2022-03-28 20:28
ok, that's weird. I think the query output is inconsistent. 

When I run a specific query 5 times results are the consistent:
```
for i in range(5):

    display(pd.DataFrame(stride.iterate('/siri_vehicle_locations/list', {
        'recorded_at_time_from': datetime.datetime(2022, 3, 1, 7, 0, tzinfo=tz.gettz('UTC')),
        'recorded_at_time_to': datetime.datetime(2022, 3, 1, 7, 5, tzinfo=tz.gettz('UTC')),
        'siri_routes__operator_ref': '3',
        'siri_routes__line_ref': '10228',
        'siri_rides__ids': '1400821'
    }, limit=100000)).recorded_at_time.tolist()) 
```
```
['2022-03-01T07:04:41+00:00',
 '2022-03-01T07:03:39+00:00',
 '2022-03-01T07:02:42+00:00',
 '2022-03-01T07:01:21+00:00',
 '2022-03-01T07:00:42+00:00']
```

but, when my query is not ride_id/line_ref specific, results are inconsistent:  
```
for i in range(5):

    res = pd.DataFrame(stride.iterate('/siri_vehicle_locations/list', {
        'recorded_at_time_from': datetime.datetime(2022, 3, 1, 7, 0, tzinfo=tz.gettz('UTC')),
        'recorded_at_time_to': datetime.datetime(2022, 3, 1, 7, 5, tzinfo=tz.gettz('UTC')),
        'siri_routes__operator_ref': '3'
    }, limit=100000))

    display(res.shape)                  
                  
    display(res[(res.siri_route__line_ref==10228)&(res.siri_ride__id==1400821)].recorded_at_time.tolist())
```
```
(8783, 22)
['2022-03-01T07:03:39+00:00',
 '2022-03-01T07:01:21+00:00',
 '2022-03-01T07:00:42+00:00',
 '2022-03-01T07:02:42+00:00']
(8783, 22)
['2022-03-01T07:04:41+00:00',
 '2022-03-01T07:03:39+00:00',
 '2022-03-01T07:01:21+00:00',
 '2022-03-01T07:00:42+00:00',
 '2022-03-01T07:02:42+00:00']
(8783, 22)
['2022-03-01T07:04:41+00:00',
 '2022-03-01T07:04:41+00:00',
 '2022-03-01T07:01:21+00:00',
 '2022-03-01T07:01:21+00:00',
 '2022-03-01T07:00:42+00:00',
 '2022-03-01T07:02:42+00:00']
(8783, 22)
['2022-03-01T07:04:41+00:00',
 '2022-03-01T07:03:39+00:00',
 '2022-03-01T07:01:21+00:00',
 '2022-03-01T07:00:42+00:00',
 '2022-03-01T07:02:42+00:00']
(8783, 22)
['2022-03-01T07:04:41+00:00',
 '2022-03-01T07:01:21+00:00',
 '2022-03-01T07:01:21+00:00',
 '2022-03-01T07:00:42+00:00',
 '2022-03-01T07:02:42+00:00']
```

What makes it ever weirder is that the total amount of records remains the same (8783) even though the content changes. 
Do you have any idea what derived this?

**Comment by OriHoch** [comment] 2022-04-03 12:55
@EyalBerger next time please include full code including imports and any other details so I can reproduce

this is the full reproduction code which should be run in a Jupyter notebook:

```
import pandas as pd
import stride
import datetime
from dateutil import tz

for i in range(5):
  res = pd.DataFrame(stride.iterate('/siri_vehicle_locations/list', {
      'recorded_at_time_from': datetime.datetime(2022, 3, 1, 7, 0, tzinfo=tz.gettz('UTC')),
      'recorded_at_time_to': datetime.datetime(2022, 3, 1, 7, 5, tzinfo=tz.gettz('UTC')),
      'siri_routes__operator_ref': '3'
  }, limit=100000))

  display(res.shape)                  

  display(res[(res.siri_route__line_ref==10228)&(res.siri_ride__id==1400821)].recorded_at_time.tolist())
```

**Comment by OriHoch** [comment] 2022-04-03 13:26
the problem was because results were not ordered, so the pagination (which `iterate` method does) didn't work proerly

fixed in https://github.com/hasadna/open-bus-stride-api/commit/76403aed6ed53ff2fb221bf00cd22d71d9be1d21 - now it always forces an order on the results

**Comment by EyalBerger** [comment] 2022-04-10 06:01
Thanks @OriHoch for taking care of it, I've rerun my test and now `siri_vehicle_locations` covers 99% of SIRI source files.

I've looked into the 1% missing data and I think there is one more issue that should be fixed. 

Those records are missing:
LineRef: `5164`
VehicleRef: `23294302`
OriginAimedDepartureTime: `2022-04-03 06:54:00+03:00`
RecordedAtTime: `2022-04-03 10:00:08+03:00` (file: `2022/04/03/07/00`), `2022-04-03 10:01:23+03:00` (file: `2022/04/03/07/01`), etc.

![image](https://user-images.githubusercontent.com/42667498/162604174-926b7191-286d-4d0f-b3c9-2de087fcebb8.png)

This is what you get when calling the API:
```
import pandas as pd
import stride
import datetime
from dateutil import tz

pd.DataFrame(stride.iterate('/siri_vehicle_locations/list', {
    'recorded_at_time_from': datetime.datetime(2022,4, 3, 7, 0, tzinfo=tz.gettz('UTC')),
    'recorded_at_time_to': datetime.datetime(2022,4, 3, 7, 6, tzinfo=tz.gettz('UTC')),
    'siri_routes__operator_ref': '3',
    'siri_routes__line_ref': '5164'
}, limit=1000))[['recorded_at_time',
                 'siri_route__line_ref',
                 'siri_route__operator_ref', 'siri_ride__scheduled_start_time','siri_ride__vehicle_ref',
                'lon','lat','siri_snapshot__snapshot_id']].sort_values(by=['siri_ride__scheduled_start_time',
                                                                          'recorded_at_time'])
```
![image](https://user-images.githubusercontent.com/42667498/162604370-e2fe8058-7bfe-414b-b6a4-0fea7d423079.png)

(Note time zone here is is UTC while in the source is IST)

As can be seen, the rows exists in the database but their` siri_ride__scheduled_start_time` is wrong - 07:00 instead of 6:54. 

Do you know why this is happening? is it because this ride planned time is 07:00 but the operator has changed it to 6:54 at some point?

**Comment by OriHoch** [comment] 2022-04-10 10:20
@EyalBerger 

The OriginAimedDepartureTime for that ride changed. In snapshot `2022/04/03/04/54` it was 07:00 and in later snapshots it changed to `06:54`

Our code uses the first OriginAimedDepartureTime it encounters for a ride and uses it for all future vehicle locations of that ride, we don't keep track of changes in OriginAimedDepartureTime

**Comment by EyalBerger** [comment] 2022-04-17 20:34
@OriHoch Thanks for checking it. I think that from analytical point of view this ride should recoded as two rides: one with OriginAimedDepartureTime of 07:00 and one of 6:54, from two reasons:
1. We want to allow users to load SIRI data is it in the original records. 
2.  Those changes could be done by operators from different purposes, and if we want to explore their nature and patterns we need the data to be identical to SIRI source files.

What do you think?

**Comment by OriHoch** [comment] 2022-04-18 05:02
let's move this to a new issue and continue work on it there: https://github.com/hasadna/open-bus/issues/390

**Comment by OriHoch** [comment] 2022-04-18 05:05
let's focus on the issue, closing this issue, please open new issues for any new issues you encounter

**Closed as completed by OriHoch** 2022-04-18 05:05 UTC
