### ISSUE TITLE
SIRI - rows with missing value in timestamp column

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#213] opened 2019-05-24 13:05 UTC
I found some weird phenomenon in SIRI - when querying with my API or with Splunk app **search** I get some rows with missing values in the timestamp column, but when querying with Splunk app **Data Exporter** everything seems to work fine.
For example -
query = `index=siri earliest=-2d latest=now route_short_name=501 |
 fields timestamp, agency_id, route_id, route_short_name, service_id, planned_start_time, bus_id, predicted_end_time, time_recorded, lat, lon, date |` 
results by timestamp - 
![image](https://user-images.githubusercontent.com/42667498/58329514-67bc2880-7e3d-11e9-94a2-e6416309d73e.png)

@cjer, @AvivSela , @evyatark  do you have any idea what might be the problem?

**Comment by cjer** [comment] 2019-05-24 16:38
Yes this is a problem in the input process which has to be resolved. The field is in a field named `xD7timestamp`. You can check both in searches for now.
As a quick fix I think I will add an alias so that this field will be available when searching on `timestamp`.

**Comment by cjer** [comment] 2019-05-24 19:37
I added an alias, so it should work as expected now. Try your original search and let me know if it works so we can close this issue.

**Comment by cjer** [comment] 2019-05-24 19:41
This should close this issue, but I will open a new one for fixing this in the input level. The `_time` for the affected events is also not correct (since it doesn't recognize the timestamp field correctly).

**Comment by cjer** [comment] 2019-05-24 20:43
So the all issues should be fixed now. Waiting for your OK @EyalBerger

**Comment by EyalBerger** [comment] 2019-05-25 19:23
Thanks! 
For testing, I queried for `search index=siri earliest=-4d latest=now route_short_name=501 | fields timestamp, agency_id, route_id, route_short_name,
service_id, planned_start_time, bus_id, predicted_end_time, time_recorded, lat, lon, date |`

It's worked fine now, no `None` values in `timestamp` column, when using the API.

But when sending this query with Splunk app **search**, I didn't get a `timestamp` column at all (I tried also to send the query without selecting specific fields).

**Comment by cjer** [comment] 2019-05-25 20:25
You are trying to query in the web interface search app?

**Comment by EyalBerger** [comment] 2019-05-25 20:35
I tried both the new API and the web interface search app for this query.

Querying with the new API worked fine. The problem I mentioned in my previous comment occurred only when querying with  the web interface search app.

**Comment by cjer** [comment] 2019-05-25 20:38
And when you try in the search tab in the open-bus app?

**Comment by EyalBerger** [comment] 2019-05-25 20:42
This is what I did...
![image](https://user-images.githubusercontent.com/42667498/58374420-b2759780-7f46-11e9-836b-5f9eac683141.png)

**Comment by cjer** [comment] 2019-05-25 20:53
And can you also give a screen capture of the fields you're getting on the left panel?

**Comment by EyalBerger** [comment] 2019-05-25 21:06
Very weird. now it's looks fine -

![image](https://user-images.githubusercontent.com/42667498/58374612-ccfd4000-7f49-11e9-9cf4-d173331cc18e.png)

I guess that something updated at midnight or you made some changes now?

**Comment by EyalBerger** [comment] 2019-05-25 21:08
I assume that now we can close this issue.

**Comment by cjer** [comment] 2019-05-25 21:09
Great. 
(it was caused by the alias. I removed it now after fixing the bad fields)

**Closed by cjer** 2019-05-25 21:09 UTC
Labels: Data, Question
