### ISSUE TITLE
changing paradigm for uploading data to Sride  

### ISSUE THREAD

**Issue by AvivSela** [hasadna/open-bus#359] opened 2021-12-15 16:28 UTC
in the beginning, we request to be able to re/upload data for a specific date in the past. I think we should rethink that request that makes our solution more complicated than it has to. I think a better assumption is that in case we will need to re/upload data for a specific date we will reprocess all the dates from that date until today.

Most of the cases that we thought about them in the planning were about some bug in our code that uploads wrong data that should be fixed or scenarios where we add more attributes and we wish to add them also on prior dates. In both cases, once we choose a date we will wish to execute the following dates too. I don't see cases where we only upload one date in the past and leave the following dates as they are.

the only case that this scenario is somehow legit is the case we are reprocessing multiple dates, we fail to insert a specific date and keep uploading the following dates - hoping that we could reupload that date again after it. I suggest that in that case, we will fail the process after the first fail. I think it is a fine price to prevent complicated code that is hard to maintain.
example of such complications:

- we execute Stride on Sunday and Friday and got the same values for a record - so we update the max date in the record so the min date is Sunday and max date is Friday. latter we executed the process for Tuesday and got different values. what should we do? assume that something happened on Tuesday so

    - the old record should be valid until Monday.
    - create new records for Tuesday
    - create another one for Wednesday -> Friday
but wait, how can we know for sure that the change was valid for one day only? could it be possible that the change was valid through Thursday?

**Comment by OriHoch** [comment] 2021-12-16 06:35
in your example - if we execute Stride on Sunday and on Friday, we will have 2 records - one for Sunday and one for Friday, we shouldn't assume it had the same data for all the intermediate dates too..

**Comment by OriHoch** [comment] 2021-12-16 06:39
There are some important advantages to being able to run on past dates:
* we can reprocess dates while keeping all the data available. If we don't allow past dates we will have to delete all data to reprocess, that means the whole system will be offline for the duration of the reprocessing (which could take a long time, even days if we have a lot of data)
* it prevents the possibility of parallel processing of dates, we will have to process sequentially
* If there is a bug on a specific date which requires our attention, the whole process is stopped until we fix it

in your example, the problem is coming from the assumption of intermediate dates, but if you remove this assumption and only handle data for the specific date like I wrote in previous comment, I don't see a problem

**Comment by OriHoch** [comment] 2021-12-16 08:00
closing this issue as we will reduce the complexity by removing min_date/max_date fields (#360)

**Closed as completed by OriHoch** 2021-12-16 08:00 UTC
Labels: Discussion
